### ISSUE TITLE
Add shortcode identifier for pasting in the post/pages

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress-research/classic-code-snippets#13]
In https://github.com/ClassicPress-research/classic-code-snippets/pull/11#pullrequestreview-556030216, there is a request that translates into a new feature.

A need to have a shortcode that can be copied and pasted from the shortcode edit page into the reference pages/posts to make it easier for one to identify the code snippet they are cross-referencing.

**Comment by ghost** [comment]
I'm going to question whether we really need this. This is a feature that is useful when there are different possible shortcode commands. In our case, there is only the one option [ccs_snippet id=xxxx]

The only thing that we need to know is the post ID and we could do that with a small function to show it in the list page.

![id](https://user-images.githubusercontent.com/46998578/102821216-d05cf400-442a-11eb-8ed6-97e4f739b76c.jpg)

**Comment by ghost** [comment]
In fact, I just edited that function and it now looks like this:

![id2](https://user-images.githubusercontent.com/46998578/102821815-da332700-442b-11eb-9f37-291a8e9fd73a.jpg)

Would that be enough?

**Comment by ghost** [comment]
This is the code I used:

```
add_filter('manage_posts_columns', 'posts_columns_id', 5);
add_action('manage_posts_custom_column', 'posts_custom_id_columns', 5, 2);

function posts_columns_id($defaults){
    $defaults['wps_post_id'] = __('Shortcode');
    return $defaults;
}

function posts_custom_id_columns($column_name, $id){
    if($column_name === 'wps_post_id'){
            echo '[css_snippets id=' . $id . ']';
    }
}
```
Just needs a condition to limit it to our CPT.

**Comment by bahiirwa** [comment]
I would say this is already an improvement. I personally like it. Nothing fancy just something to make it easier for user to work with the plugin.

**Comment by timbocode** [comment]
Yep, that's perfect. Nice one.
