### ISSUE TITLE
Need image for Update Manager

### ISSUE THREAD

**Issue by timbocode** [ClassicPress-research/classic-code-snippets#16]
As per title.

**Comment by ghost** [comment]
Something like this?

Icon...
![icon-128](https://user-images.githubusercontent.com/46998578/103250331-74b0de80-49c7-11eb-8e6d-4416f6ae43c6.png)

Banner...
![banner-772-250](https://user-images.githubusercontent.com/46998578/103250335-7a0e2900-49c7-11eb-92e8-c213825fbc26.png)

**Comment by bahiirwa** [comment]
Meets the bill.

**Comment by timbocode** [comment]
Ja, das ist sehr gut.

_Yes, it is very good._

**Comment by ghost** [comment]
Qué?

**Comment by bahiirwa** [comment]
Would you do the PR for this @simplycomputing  since you have the files?

**Comment by ghost** [comment]
I can't really test this till the Update Manager has been set up (it will only show when the plugin needs an update).

@timbocode ?

**Comment by timbocode** [comment]
Update Manager has been set up for version 1.0.0. See how far you get when you test it.

**Comment by ghost** [comment]
I've dropped back the version number but no sign of update needed yet.

**Comment by timbocode** [comment]
I'm not sure that `includes/UpdateClient.class.php` is actually being called...???

**Comment by timbocode** [comment]
It isn't (at least in my copy).

Add the following to the top of `classic-code-snippets.php` after `defined( 'ABSPATH' ) or die;`

`require_once('includes/UpdateClient.class.php');`

**Comment by ghost** [comment]
It was added in my PR #12.

What happened to it????

**Comment by timbocode** [comment]
I know. Looks like it got lost when the file was renamed.

**Comment by ghost** [comment]
Huh. I thought that was why we used github ... it's supposed to stop that from happening.

**Comment by ghost** [comment]
Yes, it got dropped in...
Plugin Rename & Code refactor.
#11

I guess renaming a file should be a straight rename. Not rename and do lots of editing as well.

**Comment by timbocode** [comment]
Yes, PRs should really cover one issue.

**Comment by timbocode** [comment]
I'll do a PR to re-add it.
