### ISSUE TITLE
Wrong code snippet shortcode examples

### ISSUE THREAD

**Issue by ghost** [ClassicPress-research/classic-code-snippets#17]
There are different examples shown on the plugin page and the code snippet list page.

![image1](https://user-images.githubusercontent.com/46998578/103489841-76691f00-4e6b-11eb-8ef5-7a366e0c0a19.jpg)

![image2](https://user-images.githubusercontent.com/46998578/103489843-79640f80-4e6b-11eb-8a7c-4f912b686068.jpg)

**Comment by ghost** [comment]
In fact there is also a THIRD option shown...

![image3](https://user-images.githubusercontent.com/46998578/103489860-b0d2bc00-4e6b-11eb-9f27-c0bbca24cf9e.jpg)

**Comment by ghost** [comment]
Suggest we standardise on [ccs_snippet id=xxx] since that is (a) shortest and (b) the one that works!

**Comment by bahiirwa** [comment]
Sorry for the jump. We settled for ccs_snippet in the last merge. No extra “s”. The css was a typo because we love style ;-)

**Comment by ghost** [comment]
OK, cool. I have this loaded up on the Classic Commerce site and it looks good (I have exported, edited, and imported all the code snippet CPTs - I added a 9 in front of all the post ids to make them unique).  That all works fine. I just have to go through and change 95 shortcodes, so thought I'd better make sure of the preferred format. :-)

**Comment by bahiirwa** [comment]
95! Really appreciate your hard work. Sorry for the endless tasks

**Comment by bahiirwa** [comment]
So can we close this?

**Comment by ghost** [comment]
Has the issue been fixed?

I notice it also says:

`Code snippets are saved or edited in the custom post type ccs_code_snippets. The plugin uses a shortcode like [ccs_code_snippet id=19] to display the code snippet on a page or post.`

in the readme.

**Comment by ghost** [comment]
... and the screenshot has css...

<img width="1072" alt="Screenshot-2" src="https://user-images.githubusercontent.com/46998578/103507160-a4be1d00-4eb2-11eb-9ee5-fdf37a52b8e3.png">

**Comment by bahiirwa** [comment]
Right! 

Tasks are as:
- [ ] Fix docs 
- [ ] Add new screenshots
- [ ] Fix whatever code generates the shortcode column on the post listing page.
- [ ] Fix the text in the plugin description.

**Comment by ghost** [comment]
Well, there's more than that.

Fix whatever code generates the shortcode column on the post listing page.
Fix  the text in the plugin description.

**Comment by bahiirwa** [comment]
Thanks updated. Let me make a PR for that.
