### ISSUE TITLE
Don't use .txt files for raw code

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress-research/classic-code-snippets#2]
As reported by @nylen https://github.com/simplycomputing/sc-display-code/issues/7

The raw code snippets should be served directly from PHP code, for example by linking to a URL like https://example.org/?p=12345&raw=true where 12345 is the ID of the code snippet post.

This can be achieved by adding a hook to the template_redirect action which checks if $_GET['raw'] is set, checks if the query is for a single post of the type registered by this plugin, and if so, outputs the raw code snippet with Content-Type: text/plain and then exits.

This will make the plugin work properly on servers where filesystem access is restricted for security reasons.

This removes 
https://github.com/ClassicPress-research/sc-display-code/blob/7e7a8fd21e007541c867f66d82cfb5767cbf2316/sc-display-code.php#L130-L146

**Comment by timbocode** [comment]
I think this can be close now?

**Comment by bahiirwa** [comment]
With the Merge, yes.
