### ISSUE TITLE
Add updater to plugin

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress-research/classic-code-snippets#3]
We need to consider adding an updater file to the plugin so that it is updatable on release here. Codepotent's plugin could do well.

**Comment by bahiirwa** [comment]
@simplycomputing Could you help with this PR? I haven't been following the latest with updater plugin.

**Comment by ghost** [comment]
OK. I'll see what I can do.

**Comment by ghost** [comment]
PR submitted!

**Comment by bahiirwa** [comment]
Much appreciated

**Comment by timbocode** [comment]
This can be closed now I presume?

**Comment by bahiirwa** [comment]
Merging of #12 will auto close this.
