### ISSUE TITLE
Proper way to enqueue the scripts and styles

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress-research/classic-code-snippets#4]
There is a proper way to enqueue these in the Head or body for ClassicPress

https://github.com/ClassicPress-research/sc-display-code/blob/7e7a8fd21e007541c867f66d82cfb5767cbf2316/sc-display-code.php#L17-L27

**Comment by bahiirwa** [comment]
Merge of #11 Also allows this to close.

**Comment by timbocode** [comment]
Closed by #11
