### ISSUE TITLE
Alternative syntax highlighter

### ISSUE THREAD

**Issue by ghost** [ClassicPress-research/classic-code-snippets#9]
For my original plugin I used highlighter.js to handle the syntax highlighting. I recently discovered that Code Potent is working on a plugin for this, so we might perhaps look at using that instead. It's not finished yet, but here is a screenshot he sent me:

![image](https://user-images.githubusercontent.com/46998578/99196761-8a38c300-27e2-11eb-9f3d-c182482ee2b2.png)

**Comment by bahiirwa** [comment]
In your opinion, would this change the whole essence of this plugin we are working on?

**Comment by ghost** [comment]
I don't really know. Code Potent just mentioned it in passing and I asked about it. But my understanding was it does the same job as highlighter.js.  It may be a while before it is available, so we should continue on with the current method and maybe think about it later.

**Comment by timbocode** [comment]
I'd personally carry on with this as originally planned. The two projects may end up serving different purposes anyway.

**Comment by bahiirwa** [comment]
> I'd personally carry on with this as originally planned. The two projects may end up serving different purposes anyway.

I think we should close this then. Thoughts @simplycomputing @timbocode

**Comment by ghost** [comment]
Yes, close this. Not sure where Code Potent is up to and it's working fine as is.

**Comment by timbocode** [comment]
Yes, close. We can always reopen if need be.
